su
rm -rf /system/app/Books
rm -rf /system/app/CalendarGooglePrebuilt
rm -rf /system/app/Chrome
rm -rf /system/app/CloudPrint2
rm -rf /system/app/DMAgent
rm -rf /system/app/Drive
rm -rf /system/app/EditorsDocs
rm -rf /system/app/EditorsSheets
rm -rf /system/app/EditorsSlides
rm -rf /system/app/FaceLock
rm -rf /system/app/FitnessPrebuilt
rm -rf /system/app/GoogleCalendarSyncAdapter
rm -rf /system/app/GoogleCamera
rm -rf /system/app/GoogleContactsSyncAdapter
rm -rf /system/app/GoogleEars
rm -rf /system/app/GoogleEarth
rm -rf /system/app/GoogleHindiIME
rm -rf /system/app/GoogleHome
rm -rf /system/app/GoogleJapaneseInput
rm -rf /system/app/GooglePinyinIME
rm -rf /system/app/GoogleTTS
rm -rf /system/app/GoogleZhuyinIME
rm -rf /system/app/Hangouts
rm -rf /system/app/KoreanIME
rm -rf /system/app/LatinImeGoogle
rm -rf /system/app/Maps
rm -rf /system/app/Music2
rm -rf /system/app/Newsstand
rm -rf /system/app/Photos
rm -rf /system/app/PlayGames
rm -rf /system/app/PlusOne
rm -rf /system/app/PrebuiltBugle
rm -rf /system/app/PrebuiltDeskClockGoogle
rm -rf /system/app/PrebuiltExchange3Google
rm -rf /system/app/PrebuiltGmail
rm -rf /system/app/PrebuiltKeep
rm -rf /system/app/PrebuiltNewsWeather
rm -rf /system/app/Street
rm -rf /system/app/TranslatePrebuilt
rm -rf /system/app/Tycho
rm -rf /system/app/Videos
rm -rf /system/app/Wallet
rm -rf /system/app/YouTube
rm -rf /system/app/talkback
rm -rf /system/etc/permissions/com.google.android.dialer.support.xml
rm -rf /system/etc/permissions/com.google.android.maps.xml
rm -rf /system/etc/permissions/com.google.android.media.effects.xml
rm -rf /system/etc/permissions/com.google.widevine.software.drm.xml
rm -rf /system/etc/preferred-apps/google.xml
rm -rf /system/etc/sysconfig/google.xml
rm -rf /system/etc/sysconfig/google_build.xml
rm -rf /system/framework/com.google.android.dialer.support.jar
rm -rf /system/framework/com.google.android.maps.jar
rm -rf /system/framework/com.google.android.media.effects.jar
rm -rf /system/framework/com.google.widevine.software.drm.jar
rm -rf /system/lib/libfacelock_jni.so
rm -rf /system/lib/libfilterpack_facedetect.so
rm -rf /system/lib/libjni_latinimegoogle.so
rm -rf /system/priv-app/AndroidForWork
rm -rf /system/priv-app/ConfigUpdater
rm -rf /system/priv-app/GCS
rm -rf /system/priv-app/GoogleBackupTransport
rm -rf /system/priv-app/GoogleFeedback
rm -rf /system/priv-app/GoogleLoginService
rm -rf /system/priv-app/GoogleOneTimeInitializer
rm -rf /system/priv-app/GooglePartnerSetup
rm -rf /system/priv-app/GoogleServicesFramework
rm -rf /system/priv-app/Phonesky
rm -rf /system/priv-app/PrebuiltGmsCore
rm -rf /system/priv-app/SetupWizard
rm -rf /system/priv-app/TagGoogle
rm -rf /system/priv-app/Velvet
rm -rf /system/usr/srec/en-US/
rm -rf /system/vendor/lib/libfrsdk.so
rm -rf /system/vendor/pittpatt/